name: Ersilia model eos2r5a output prediction
on: push                                         

permissions:
  contents: read

env:
  MODEL_ID: eos2r5a

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          repository: ersilia-os/ersilia

      - name: Add conda to system path
        run: echo $CONDA/bin >> $GITHUB_PATH

      - name: Source conda
        run: source $CONDA/etc/profile.d/conda.sh

      - name: Set Python to 3.10.10
        run:
         conda install -y python=3.10.10

      - name: Install dependencies
        run: |
          source activate
          conda init
          conda install git-lfs -c conda-forge
          git-lfs install
          conda install gh -c conda-forge
          
      - name: Install ersilia
        run: |
          source activate
          python --version
          echo "After conda init"
          conda init
          python -m pip install -e .[test]

  predict:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Predict output
        run: |
          echo "Sample model id selected: $MODEL_ID"
          ersilia fetch $MODEL_ID
          ersilia serve $MODEL_ID
          echo "$MODEL_ID succesfully fetched and served"
          ersilia sample -n 100 -f input.csv
          ersilia api -i input.csv -o output.csv

      - name: Close Ersilia session 
        run: ersilia close
          
      - name: Create zip bundle
        run: zip -r ${{ github.sha }}.zip .
             
      - name: Archive artifact
        uses: actions/upload-artifact@master
        with:
          name: zipped-bundle
          path: ${{ github.sha }}.zip

